name: Deploy to Fly on push to main
on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Nix packages
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix packages
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Cache rust dependencies and build output
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build the Leptos project to `musl` output
        run: nix-shell --run 'cargo leptos build --release'
      - name: Deploy a docker container to Fly.io
        run: nix-shell --run 'fly deploy'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
