name: Generate lighthouse test report on PR
on:
    pull_request:
        branches: [ main, lighthouse_testing_pipeline ]
        
jobs:
    lhci:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Install Node.js
            uses: actions/setup-node@v4
            with: 
                node-version: 20
          - run: npm install


          # - name: Install Lighthouse
          #   run: npm install -g @lhci/cli@0.13.x

          # - name: Run Lighthouse
          #   id: lhcitests
          #   run: lhci autorun
            # env: 
            #     LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

          # - name: install playwright
          #   run: npx playwright install    

          # - name: run playwright
          #   id: tests
          #   run: npx playwright test --project=firefox 
          #   # continue-on-error: true
            
          # - name: Notify on Google Chat 
          #   uses: Co-qn/google-chat-notification@v1
          #   with:
          #     name: test
          #     url: ${{ secrets.TEST_WEBHOOK_URL }}
          #     status: ${{ steps.tests.outcome }}
          
    # close-pr:
    #     if: ${{ needs.lhci.result != 'failure' }}
    #     needs: lhci 
    #     runs-on: ubuntu-latest
    #     steps:      
    #     - run: gh pr close "$NUMBER" --comment "$COMMENT"
    #       env:
    #           GITHUB_TOKEN: ${{ secrets.NEW_GITHUB_APP_TOKEN }}
    #           GH_REPO: ${{ github.repository }}
    #           NUMBER: ${{ github.event.number }}
    #           COMMENT: >
    #             "Playwright tests failed. Closing this pull request."

         
    
    
          # - name: Check test result and comment
          #   uses: peter-evans/create-or-update-comment@v1
          #   with:
          #     token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          #     issue-number: ${{ github.event.pull_request.number }}
          #     body: |
          #       ${{ steps.tests.outcome == 'failed' && 'Test failed, Please check logs for details.' || 'Test passed :heavy_check_mark:'  }}


          # # foo lhci test to comment Lighthouse score to PR
          # - uses: actions/checkout@master
          # - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
          # - name: lighthouseCheck
          #   uses: foo-software/lighthouse-check-action@master
          #   with:
          #     outputDirectory: ${{ github.workspace }}/tmp/artifacts
          #     gitHubAccessToken: ${{ secrets.NEW_GITHUB_APP_TOKEN }}
          #     urls: 'https://yral.com/'
         
          # - name: Notify on Google Chat 
          #   uses: Co-qn/google-chat-notification@v1
          #   with:
          #     name: test
          #     url: ${{ secrets.TEST_WEBHOOK_URL }}
          #     status: ${{ steps.lighthouseCheck.outputs }}

              
          # - name: Verify Lighthouse Check results
          #   uses: foo-software/lighthouse-check-status-action@master
          #   with:
          #     lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          #     minAccessibilityScore: "90"
          #     minBestPracticesScore: "90"
          #     minPerformanceScore: "50"
          #     minProgressiveWebAppScore: "50"
          #     minSeoScore: "50"


          # - name: Upload artifacts
          #   uses: actions/upload-artifact@master
          #   with:
          #     name: Lighthouse reports
          #     path: ${{ github.workspace }}/tmp/artifacts


          # call another repo as post deploy action
          - name: Trigger a workflow in another repo
            uses: actions/github-script@v5
            with:
                script: |
                  github.rest.repos.createDispatchEvent({
                    owner: 'go-bazzinga',
                    repo: 'hot-or-not-web-leptos-ssr-e2e-test',
                    event_type: 'call',
                    
                    client_payload: { ref: "playwright_testing" }
                  });
                github-token: ${{ secrets.NEW_GITHUB_APP_TOKEN }}
